#!/bin/bash

# Options for the menu
options="Shutdown\nKill\nReboot\nLogout\nzzz\nLock"

# Show dmenu and get the selection
choice=$(echo -e $options | rofi -dmenu -i -p "Power Menu:")

# Execute based on the selection
case "$choice" in
	Kill)
        ps -u "$USER" -o pid,comm,%cpu,%mem | rofi -dmenu -i -c -l 10 -p Kill: | awk '{print $1}' | xargs -r kill 
        ;;
    Shutdown)
        systemctl poweroff
        ;;
    Reboot)
        systemctl reboot
        ;;
    Logout)
        # For example, if using i3
        i3-msg exit
        ;;
    zzz)
        systemctl suspend
        ;;
    Lock)
        # Example using i3lock
        i3lock -i "$HOME/.dotfiles/i3/Wallpaper/Lock/Untitled.jpg"
        ;;
esac
