#!/bin/bash
command -v brightnessctl >/dev/null || exit 1
current=$(brightnessctl get)
max=$(brightnessctl max)
percent=$(( (current * 100 + max / 2) / max ))

# notify-send \
#   -a "Brightness" \
#   -h int:value:"$percent" \
#   -h string:x-dunst-stack-tag:brightness \
#   "Brightness" "${percent}%"

command -v doi-bright >/dev/null || exit 0
doi-bright get
